-- PostgreSQL + PostGIS Schema for NexFlow Urban Freight Intelligence Platform
-- Pilot District: Kolkata Burrabazar / Posta

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('ADMIN', 'FLEET_OPERATOR', 'DRIVER', 'ANALYST')),
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- FLEETS TABLE
CREATE TABLE IF NOT EXISTS fleets (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    operator_id UUID REFERENCES users(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- VEHICLES TABLE
CREATE TABLE IF NOT EXISTS vehicles (
    id VARCHAR(100) PRIMARY KEY,
    fleet_id UUID REFERENCES fleets(id) ON DELETE SET NULL,
    vehicle_no VARCHAR(50) UNIQUE NOT NULL,
    type VARCHAR(50) NOT NULL,
    capacity_kg INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'IDLE',
    driver_name VARCHAR(255),
    route_version INTEGER DEFAULT 1,
    eta VARCHAR(50),
    geom GEOMETRY(Point, 4326),
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- DRIVERS TABLE
CREATE TABLE IF NOT EXISTS drivers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    vehicle_id VARCHAR(100) REFERENCES vehicles(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    status VARCHAR(50) DEFAULT 'OFFLINE',
    last_sync TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- BAYS TABLE
CREATE TABLE IF NOT EXISTS bays (
    id VARCHAR(100) PRIMARY KEY,
    bay_id VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    zone VARCHAR(100) NOT NULL,
    state VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE',
    vehicle_type_allowed VARCHAR(50) DEFAULT 'ANY',
    max_service_time_min INTEGER DEFAULT 30,
    utilization_pct INTEGER DEFAULT 0,
    geom GEOMETRY(Point, 4326),
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- DELIVERIES TABLE
CREATE TABLE IF NOT EXISTS deliveries (
    id VARCHAR(100) PRIMARY KEY,
    tracking_id VARCHAR(100) UNIQUE NOT NULL,
    pickup_address VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    window_start VARCHAR(50) NOT NULL,
    window_end VARCHAR(50) NOT NULL,
    priority VARCHAR(50) NOT NULL DEFAULT 'MEDIUM',
    weight_kg INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    assigned_vehicle_id VARCHAR(100) REFERENCES vehicles(id) ON DELETE SET NULL,
    assigned_bay_id VARCHAR(100) REFERENCES bays(id) ON DELETE SET NULL,
    pickup_geom GEOMETRY(Point, 4326),
    drop_geom GEOMETRY(Point, 4326),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- BAY SLOTS TABLE
CREATE TABLE IF NOT EXISTS bay_slots (
    id VARCHAR(100) PRIMARY KEY,
    slot_id VARCHAR(100) NOT NULL,
    bay_id VARCHAR(100) REFERENCES bays(id) ON DELETE CASCADE,
    delivery_id VARCHAR(100) REFERENCES deliveries(id) ON DELETE SET NULL,
    start_time VARCHAR(50) NOT NULL,
    end_time VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE'
);

-- INCIDENTS TABLE
CREATE TABLE IF NOT EXISTS incidents (
    id VARCHAR(100) PRIMARY KEY,
    incident_id VARCHAR(100) UNIQUE NOT NULL,
    type VARCHAR(50) NOT NULL,
    severity VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    description TEXT,
    affected_segment VARCHAR(100),
    geom GEOMETRY(Point, 4326),
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ROUTE PLANS TABLE
CREATE TABLE IF NOT EXISTS route_plans (
    id VARCHAR(100) PRIMARY KEY,
    route_id VARCHAR(100) UNIQUE NOT NULL,
    vehicle_id VARCHAR(100) REFERENCES vehicles(id) ON DELETE CASCADE,
    distance_km DOUBLE PRECISION NOT NULL,
    duration_min INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    route_version INTEGER DEFAULT 1,
    geometry JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- PREDICTIONS TABLE
CREATE TABLE IF NOT EXISTS predictions (
    id VARCHAR(100) PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    unit VARCHAR(50) NOT NULL,
    zone VARCHAR(100) NOT NULL,
    horizon_min INTEGER NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    model VARCHAR(100) NOT NULL,
    version VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- OPTIMIZATION RUNS TABLE
CREATE TABLE IF NOT EXISTS optimization_runs (
    id VARCHAR(100) PRIMARY KEY,
    run_id VARCHAR(100) UNIQUE NOT NULL,
    status VARCHAR(50) NOT NULL,
    vehicles_count INTEGER NOT NULL,
    deliveries_count INTEGER NOT NULL,
    bays_count INTEGER NOT NULL,
    objective_value DOUBLE PRECISION NOT NULL,
    solver_ms INTEGER NOT NULL,
    trigger_event VARCHAR(100) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- AUDIT EVENTS TABLE
CREATE TABLE IF NOT EXISTS audit_events (
    id VARCHAR(100) PRIMARY KEY,
    event_id VARCHAR(100) UNIQUE NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    actor VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100) NOT NULL,
    metadata JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- SPATIAL INDEXES
CREATE INDEX IF NOT EXISTS idx_bays_geom ON bays USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_vehicles_geom ON vehicles USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_incidents_geom ON incidents USING GIST (geom);
